### ISSUE TITLE
About pc.calculate_interactions and complete environment config

### ISSUE THREAD

**Issue by ZerinHwang03** [cch1999/posecheck#1]
Dear authors,
Thanks for sharing this amazing work.
However, we met errors when we run pc.calculate_interactions(): 

```
Traceback (most recent call last):
File "/homre/miniconda3/envs/pc/lib/python3.8/site-packages/ loguru/_locks_machinery.py", line 29, in release_locks
def release locks():
File "/home/miniconda3/envs/pc/lib/python3.8/site-packages/gsd/_init__.py", line 24, in <lambda>
signal.signal(signal.SIGTERM，lambda n,f; sys.exit(1)
SystemExit: 1
Exception ignored in: <function release locks at 0x7fa895bcb940>
Traceback (most recent call last):File "/home/miniconda3/envs/pc/lib/python3.8/site-packages/loguru/_locks_machinery.py", line 29,in release_locks
def release locks():
File "/home/miniconda3/envs/pc/lib/python3.8/site-packages/gsd/ init .py", line 24,in <lambda>
signal.signal(signal.SIGTERM,lambda n,f: sys.exit(1))
SystemExit: 1
```

Can you suggest what to do?

And could you please provide the complete environment configs of posecheck? that would be helpful.

**Comment by cch1999** [comment]
Hi Zerin

Thanks for your kind words and sorry for the delay in replying to your issue. I have not encountered that problem before but will look into it. (Although I suspect your python may be too old).

In the meantime, I have pushed the full environment config to the main branch.

Charlie
